### ISSUE TITLE
提示Module not found: Error

### ISSUE THREAD

**Issue by ehxu** [frankli0324/ctfd-pages-theme#2]
请问大佬这个主题支持哪个版本的CTFd，一直提示Module not found: Error错误，请问这该怎么解决？

![image](https://user-images.githubusercontent.com/72177839/127900885-dff44ced-2184-4bea-9bf2-b559e74e7332.png)

**Comment by frankli0324** [comment]
嗯。。由于CTFd迷惑的theming系统，暂时没找到比较优雅的patch主题的办法，本仓库也好久没更新了。。
实际上我只修改了 `assets/js/pages/challenges.js` 以及对应的 `templates/challenges.html`，可以在官方core的基础上自行修改，有空了我也更新一下这个仓库
