### ISSUE TITLE
啥时候更新啊 师傅

### ISSUE THREAD

**Issue by kevien** [frankli0324/ctfd-pages-theme#4]
求更

**Comment by frankli0324** [comment]
对于CTFShow为了实现局部加载我是新加了一个接口用于枚举所有category。。所以可能没有泛用性了，再者我已经毕业了可能后面很少会有机会玩这些了。。Orz
要不我先把目前的新开个分支push上来再说

**Comment by frankli0324** [comment]
唉。。老了，整个这破事花了这么长时间
