### ISSUE TITLE
缺少使用指引

### ISSUE THREAD

**Issue by C3ting** [frankli0324/ctfd-pages-theme#5]
放到文件中后，编译会报错，请问有详细点的使用教程么，这个插件在网上的相关的内容太少了

**Comment by frankli0324** [comment]
请提供详细的错误信息

**Comment by C3ting** [comment]
![image](https://github.com/frankli0324/ctfd-pages-theme/assets/92133551/35c56fc7-8ee2-47dd-adac-34a6bb5002ee)
我在安装好ctfd 3.5.0 的基础上，使用git clone https://github.com/frankli0324/ctfd-pages-theme CTFd/themes/pages后
然后再ctfd的根目录执行npm i && npm run build 构建项目，但是报错了，报错信息如上，麻烦大佬看看是什么问题。还有这个主题需要加一个路由，路由加在/api/v1/challenges.py文件的什么位置呢，有例子么。跪求大佬解答

**Comment by frankli0324** [comment]
不需要build，直接切换主题即可。

categories示例：

```py
@challenges_namespace.route("/categories")
class ChallengeCategories(Resource):
    @challenges_namespace.doc(description="Endpoint to get Challenge categories in bulk")
    @cache.memoize(timeout=60)
    def get(self):
        chal_q = (Challenges.query.with_entities(Challenges.category).group_by(Challenges.category))
        if not is_admin() or request.args.get("view") != "admin":
            chal_q = chal_q.filter(and_(Challenges.state != "hidden", Challenges.state != "locked"))
        return {"success": True, "data": [i.category for i in chal_q]}
```

加载文件哪里都行

**Comment by C3ting** [comment]
![image](https://github.com/frankli0324/ctfd-pages-theme/assets/92133551/6df08b40-c75e-41ca-b23f-a781b595dd94)
实际测试，加上去后，会出现该错误，在ctfd的容器中。

**Comment by frankli0324** [comment]
@C3ting 仅供参考

**Comment by C3ting** [comment]
也就是说，这个枚举题目的，需要另外增加数据库字段（题目部分），然后在api接口部分写接口 枚举类型 是吧？

**Comment by C3ting** [comment]
![image](https://github.com/frankli0324/ctfd-pages-theme/assets/92133551/67515fbe-f0f7-4ad7-b2e0-1c545912d9b1)
API修改完成，但是在切换主题后出现该问题

**Comment by fengpiaohongjishuzhongxin** [comment]
我的情况是无法适配 ctfd 3.5.3 
在challenges.py中增加了分类的路由,能正常显示了,但是无法正常获取其他数据等,估计是CSRF校验码的问题,但是js代码都经过压缩了,实在不太好修改

**Comment by frankli0324** [comment]
我周末录个视频吧，从clone CTFd开始

**Comment by frankli0324** [comment]
https://www.bilibili.com/video/BV1g14y117fL/
录的时候忘了调分辨率了。。但是可以看清

**Comment by mcyydscc** [comment]
佬，什么时候支持3.6.0

**Comment by frankli0324** [comment]
@mcyydscc 我在录制时使用的就是3.6.0

**Comment by imLZH1** [comment]
3.5.0 为什么不支持啊呜呜呜
